services:
  - type: web
    name: biochar-rag-api
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    disk:
      name: biochar-data
      mountPath: /opt/render/project/src/data
      sizeGB: 5

    envVars:
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: EMAIL_DATA_PATH
        value: /opt/render/project/src/data/emails_clean_normalized.csv
      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_MODEL
        value: deepseek-ai/DeepSeek-R1-0528
